---
title: "Home"
---

# World Happiness Report: A Visualization Redesign

Welcome to our project website. The goal of this project is to analyze and redesign visualizations based on the World Happiness Report dataset.

Welcome to a comprehensive evaluation of human subjective well-being.

•⁠  ⁠Explore Trends:  Our visualizations chart the global Life Ladder (Happiness Score) from 2008 through the most recent data, offering a multi-dimensional view of how contentment has shifted over time. 
•⁠  ⁠Pillars of Prosperity: Dive into the economic and social pillars that underpin joy, revealing how factors like GDP per Capita, Social Support, and Freedom shape a nation's collective mood.
•⁠  ⁠Regional Disparity:  Illuminate the stark contrasts in life evaluation, showcasing the disparity in happiness as we compare outcomes across various global regions.
•⁠  ⁠Factor Influence:  Unravel the complex balance of variables, highlighting which factors exert the most significant influence on a country's average life evaluation score.
•⁠  ⁠Data Chapters: Each visualization is a chapter in this ongoing global narrative, translating complex statistics into clear, actionable insights.
Join the Exploration:  Through our analysis, we aim to shed light on the core drivers of human happiness, providing valuable insights into this critical measure of global public health and policy success. 

Navigate through the pages using the bar at the top to learn more about our team, view the project analysis, and see the source code.